services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: retail_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d retail_sales"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/retail_sales
    depends_on:
      db:
        condition: service_healthy